/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Perpustakaan.form_utama;

import java.io.File;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

import Perpustakaan.form_master.DataBuku;
import Perpustakaan.form_master.Form_Pengembalian;
import Perpustakaan.form_master.Form_Peminjaman;
import Perpustakaan.form_master.Inventaris;
import javax.swing.JFrame;

/**
 *
 * @author Acer
 */
public class Menu_Utama extends javax.swing.JFrame {

    /**
     * Creates new form Form_Login
     */
    public Menu_Utama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        master = new javax.swing.JMenu();
        admin = new javax.swing.JMenuItem();
        anggota = new javax.swing.JMenuItem();
        buku = new javax.swing.JMenuItem();
        inv = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        peminjaman = new javax.swing.JMenuItem();
        pengembalian = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        Laporan_Buku = new javax.swing.JMenuItem();
        Laporan_Peminjaman = new javax.swing.JMenuItem();
        Laporan_Pengembalian = new javax.swing.JMenuItem();
        inventaris = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setToolTipText("");
        jPanel2.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Aplikasi Perpustakaan MA Al-Fathiyah");

        keluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        keluar.setText("Logout");
        keluar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluarMouseClicked(evt);
            }
        });
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Perpustakaan/img/bg.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(156, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        master.setText("Master");
        master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masterActionPerformed(evt);
            }
        });

        admin.setText("Admin");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        master.add(admin);

        anggota.setText("Anggota");
        anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anggotaActionPerformed(evt);
            }
        });
        master.add(anggota);

        buku.setText("Buku");
        buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukuActionPerformed(evt);
            }
        });
        master.add(buku);

        inv.setText("Inventaris");
        inv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invActionPerformed(evt);
            }
        });
        master.add(inv);

        jMenuBar1.add(master);

        transaksi.setText("Transaksi");

        peminjaman.setText("Peminjaman Buku");
        peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanActionPerformed(evt);
            }
        });
        transaksi.add(peminjaman);

        pengembalian.setText("Pengembalian Buku");
        pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalianActionPerformed(evt);
            }
        });
        transaksi.add(pengembalian);

        jMenuBar1.add(transaksi);

        laporan.setText("Laporan");
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });

        jMenuItem6.setText("Laporan Data Anggota");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        laporan.add(jMenuItem6);

        Laporan_Buku.setText("Laporan Data Buku");
        Laporan_Buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Laporan_BukuActionPerformed(evt);
            }
        });
        laporan.add(Laporan_Buku);

        Laporan_Peminjaman.setText("Laporan Data Peminjaman");
        Laporan_Peminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Laporan_PeminjamanActionPerformed(evt);
            }
        });
        laporan.add(Laporan_Peminjaman);

        Laporan_Pengembalian.setText("Laporan Data Pengembalian");
        Laporan_Pengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Laporan_PengembalianActionPerformed(evt);
            }
        });
        laporan.add(Laporan_Pengembalian);

        inventaris.setText("Laporan Inventaris");
        inventaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarisActionPerformed(evt);
            }
        });
        laporan.add(inventaris);

        jMenuBar1.add(laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try{
           String namaFile = "src/LaporanPerpus/LapAnggota.jasper";
           Connection conn = new koneksi().connect();
           HashMap parameter = new HashMap();
           File report_file = new File(namaFile);
           JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
           JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
           JasperViewer.viewReport(jasperPrint, false);
           JasperViewer.setDefaultLookAndFeelDecorated(true);
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void pengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalianActionPerformed
       Form_Pengembalian frmFPM = new Form_Pengembalian();
        frmFPM.setVisible(true);
    }//GEN-LAST:event_pengembalianActionPerformed

    private void peminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamanActionPerformed
       Form_Peminjaman frmFP = new Form_Peminjaman();
        frmFP.setVisible(true);
    }//GEN-LAST:event_peminjamanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
       Form_Login frmFL = new Form_Login();
        frmFL.setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
       
    }//GEN-LAST:event_laporanActionPerformed

    private void Laporan_BukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Laporan_BukuActionPerformed
       try{
           String namaFile = "src/LaporanPerpus/LapDataBuku.jasper";
           Connection conn = new koneksi().connect();
           HashMap parameter = new HashMap();
           File report_file = new File(namaFile);
           JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
           JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
           JasperViewer.viewReport(jasperPrint, false);
           JasperViewer.setDefaultLookAndFeelDecorated(true);
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_Laporan_BukuActionPerformed

    private void Laporan_PeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Laporan_PeminjamanActionPerformed
        try{
           String namaFile = "src/LaporanPerpus/LapPeminjaman.jasper";
           Connection conn = new koneksi().connect();
           HashMap parameter = new HashMap();
           File report_file = new File(namaFile);
           JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
           JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
           JasperViewer.viewReport(jasperPrint, false);
           JasperViewer.setDefaultLookAndFeelDecorated(true);
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_Laporan_PeminjamanActionPerformed

    private void Laporan_PengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Laporan_PengembalianActionPerformed
         try{
           String namaFile = "src/LaporanPerpus/LapPengembalian1.jasper";
           Connection conn = new koneksi().connect();
           HashMap parameter = new HashMap();
           File report_file = new File(namaFile);
           JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
           JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
           JasperViewer.viewReport(jasperPrint, false);
           JasperViewer.setDefaultLookAndFeelDecorated(true);
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_Laporan_PengembalianActionPerformed

    private void masterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masterActionPerformed

    }//GEN-LAST:event_masterActionPerformed

    private void bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukuActionPerformed
        DataBuku frmBku = new DataBuku();
        frmBku.setVisible(true);
    }//GEN-LAST:event_bukuActionPerformed

    private void anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anggotaActionPerformed
        Form_Anggota frmFA = new Form_Anggota();
        frmFA.setVisible(true);
    }//GEN-LAST:event_anggotaActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        Form_Admin frmAM = new Form_Admin();
        frmAM.setVisible(true);
    }//GEN-LAST:event_adminActionPerformed

    private void invActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invActionPerformed
        Inventaris inv = new Inventaris();
        inv.setVisible(true);
    }//GEN-LAST:event_invActionPerformed

    private void keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarMouseClicked

    private void inventarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarisActionPerformed
        try{
           String namaFile = "src/LaporanPerpus/LapInventaris.jasper";
           Connection conn = new koneksi().connect();
           HashMap parameter = new HashMap();
           File report_file = new File(namaFile);
           JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
           JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
           JasperViewer.viewReport(jasperPrint, false);
           JasperViewer.setDefaultLookAndFeelDecorated(true);
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_inventarisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Laporan_Buku;
    private javax.swing.JMenuItem Laporan_Peminjaman;
    private javax.swing.JMenuItem Laporan_Pengembalian;
    private javax.swing.JMenuItem admin;
    private javax.swing.JMenuItem anggota;
    private javax.swing.JMenuItem buku;
    private javax.swing.JMenuItem inv;
    private javax.swing.JMenuItem inventaris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton keluar;
    public static javax.swing.JMenu laporan;
    public static javax.swing.JMenu master;
    private javax.swing.JMenuItem peminjaman;
    private javax.swing.JMenuItem pengembalian;
    public static javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables
}
